### ISSUE TITLE
大佬有联系方式不

### ISSUE THREAD

**Issue by jackKiZhu** [redbg/CS2-Internal#1]
如题

**Comment by redbg** [comment]
705642344@qq.com
有新的建议或者 提交bug，可以联系我。此项目我会长期维护

**Comment by jackKiZhu** [comment]
话说大佬都hook dx11了，为什么不加上透视捏

**Comment by redbg** [comment]
以后会加，但也只是为了方便调试。从我个人角度来讲，透视没啥必要，我不喜欢把游戏画面弄的乱七八糟，所以先不写

**Comment by jackKiZhu** [comment]
> 以后会加，但也只是为了方便调试。从我个人角度来讲，透视没啥必要，我不喜欢把游戏画面弄的乱七八糟，所以先不写

好滴
