### ISSUE TITLE
新增了一段自瞄时候用的压枪控制代码，测试下来感觉还行，UP有空了可以看下

### ISSUE THREAD

**Issue by swmonoku** [redbg/CS2-Internal#3]
if (localPlayerPawn->m_iShotsFired() > 1)
                {
                    CS2::SDK::CUtlVector<SDK::QAngle> punchCache = localPlayerPawn->m_aimPunchCache();
                    
                    if (punchCache.m_Size <= 0 || punchCache.m_Size > 0xFFFF)
                    {
                        return;
                    }
                    
                    aimAngle.y = aimAngle.y - punchCache.m_Elements->yaw * 2.0f;
                    aimAngle.x = aimAngle.x - punchCache.m_Elements->pitch * 2.0f;
                }

                Offset::SetViewAngle(Offset::CSGOInput, 0, aimAngle);

有机会了也可以多多交流，希望能跟UP主学习

**Comment by redbg** [comment]
现在加了，效果很不错。多谢

**Comment by jackKiZhu** [comment]
牛逼！

**Comment by jackKiZhu** [comment]
好奇怪我单独弄个压枪好像没效果。

void RECS()
{
    if (!CS2::Interface::EngineClient->IsInGame())
        return;

    auto localPlayerController = *CS2::Offset::LocalPlayerController;
    auto localPlayerPawn       = static_cast<CS2::Class::C_CSPlayerPawn *>(localPlayerController->m_hPawn().Get());

    if (!localPlayerController->m_bPawnIsAlive())
        return;

    SDK::Vector aimAngle = {};

    if (localPlayerPawn->m_iShotsFired() && localPlayerPawn->m_aimPunchCache().m_Size)
    {
        SDK::Vector aimPunchAngle = localPlayerPawn->m_aimPunchCache().m_Elements[localPlayerPawn->m_aimPunchCache().m_Size - 1];

        aimAngle.x = aimAngle.x - (aimPunchAngle.x * 2.0f);
        aimAngle.y = aimAngle.y - (aimPunchAngle.y * 2.0f);
    }

    Offset::SetViewAngle(Offset::CSGOInput, 0, SDK::NormalizeAngles(aimAngle));
}

**Comment by redbg** [comment]
aimAngle 凭空来的，当然不行啦。压抢最好配合自瞄比较好，先计算出来aimAngle

**Comment by jackKiZhu** [comment]
> aimAngle 凭空来的，当然不行啦。压抢最好配合自瞄比较好，先计算出来aimAngle

噢，那我应该先获取自身的aimAngle ，才能压枪噢，因为我想弄个全局压枪舒服一点。
